name: tab

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🔎 Check IP
        run: curl https://api.ipify.org

    
       # Add the following steps to get the IP addresses of the GitHub Actions runners
      - name: Get IP addresses
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Output IP addresses
        run: echo "IPv4: ${{ steps.ip.outputs.ipv4 }}\nIPv6: ${{ steps.ip.outputs.ipv6 }}"

  test:
    name: Cypress Cloud Tests
    runs-on: ubuntu-20.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 5 copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: cypress run
        uses: cypress-io/github-action@v4
        with: 
          command: npm run cypress-dashboard-parallel
